import { useState, useEffect } from "react";
import { useParams, Link } from "react-router-dom";
import StaffLayout from "../../components/StaffLayout";
import salesInvoicesService from "../../services/salesInvoicesService";
import { Receipt, Mail, Calendar, User, Printer, ArrowLeft, Send, CheckCircle, AlertCircle } from "lucide-react";

export default function StaffInvoiceDetailPage() {
  const { id } = useParams();
  const [invoice, setInvoice] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [emailStatus, setEmailStatus] = useState("");
  const [emailLoading, setEmailLoading] = useState(false);

  const loadData = async () => {
    try {
      setLoading(true);
      setError("");
      const res = await salesInvoicesService.getSalesInvoiceById(id);
      setInvoice(res?.result || res);
    } catch (err) {
      console.error(err);
      setError(err.message || "Failed to load sales invoice details.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (id) {
      loadData();
    }
  }, [id]);

  const handleSendEmail = async () => {
    try {
      setEmailLoading(true);
      setEmailStatus("");
      await salesInvoicesService.sendInvoiceEmail(id);
      setEmailStatus("Invoice email sent successfully!");
    } catch (err) {
      console.error(err);
      setEmailStatus("Failed to send invoice email.");
    } finally {
      setEmailLoading(false);
    }
  };

  if (loading) {
    return (
      <StaffLayout pageTitle="Loading Invoice...">
        <div className="flex justify-center items-center py-20">
          <div className="h-8 w-8 animate-spin rounded-full border-b-2 border-slate-900" />
        </div>
      </StaffLayout>
    );
  }

  if (error || !invoice) {
    return (
      <StaffLayout pageTitle="Invoice Details Error">
        <div className="bg-red-50 p-4 rounded-3xl text-red-700 text-center max-w-md mx-auto">
          <p>{error || "Sales invoice could not be found."}</p>
          <Link to="/staff/invoices" className="text-sm font-semibold mt-3 inline-block underline">
            Back to Invoices
          </Link>
        </div>
      </StaffLayout>
    );
  }

  return (
    <StaffLayout pageTitle={`Invoice ${invoice.invoiceNumber}`} subtitle="Review details, payments, and dispatch copy to client">
      <div className="max-w-3xl mx-auto space-y-6">
        {/* Back and Action Buttons */}
        <div className="flex items-center justify-between">
          <Link
            to="/staff/invoices"
            className="text-xs font-semibold text-slate-600 hover:text-slate-900 inline-flex items-center gap-1"
          >
            <ArrowLeft size={14} /> Back to Invoices
          </Link>

          <div className="flex gap-2">
            <button
              onClick={() => window.print()}
              className="px-3.5 py-2 border border-slate-200 rounded-xl text-xs font-semibold text-slate-700 bg-white hover:bg-slate-50 inline-flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <Printer size={14} /> Print
            </button>
            <button
              onClick={handleSendEmail}
              disabled={emailLoading}
              className="px-4 py-2 bg-sky-600 hover:bg-sky-700 disabled:bg-sky-400 text-white rounded-xl text-xs font-semibold inline-flex items-center gap-1.5 cursor-pointer shadow-xs"
            >
              <Send size={14} /> {emailLoading ? "Sending..." : "Send Email"}
            </button>
          </div>
        </div>

        {emailStatus && (
          <div
            className={`p-4 rounded-2xl text-sm flex items-center gap-2 ${
              emailStatus.includes("successfully")
                ? "bg-green-50 border border-green-200 text-green-700"
                : "bg-red-50 border border-red-200 text-red-700"
            }`}
          >
            {emailStatus.includes("successfully") ? <CheckCircle size={16} /> : <AlertCircle size={16} />}
            {emailStatus}
          </div>
        )}

        {/* Invoice Card */}
        <div className="bg-white border border-slate-200 rounded-3xl p-8 shadow-xs space-y-8 print:border-none print:shadow-none">
          {/* Header */}
          <div className="flex justify-between items-start border-b border-slate-100 pb-6">
            <div>
              <span className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Sales Invoice</span>
              <h2 className="text-2xl font-black text-slate-900 mt-1">{invoice.invoiceNumber}</h2>
              <p className="text-xs text-slate-400 mt-1">
                Generated by: {invoice.createdByStaffName || "Service Staff"}
              </p>
            </div>
            <div className="text-right">
              <span
                className={`px-3 py-1 rounded-md text-xs font-bold uppercase tracking-wider ${
                  invoice.status === "Paid"
                    ? "bg-green-50 text-green-700"
                    : invoice.status === "Credit" || invoice.status === "Overdue"
                    ? "bg-red-50 text-red-700"
                    : "bg-amber-50 text-amber-700"
                }`}
              >
                {invoice.status}
              </span>
            </div>
          </div>

          {/* Details Grid */}
          <div className="grid sm:grid-cols-2 gap-6 text-xs border-b border-slate-100 pb-6">
            <div className="space-y-2">
              <p className="uppercase font-bold text-slate-400 tracking-wider">Billed To</p>
              <div className="space-y-1">
                <p className="font-bold text-slate-800 text-sm">{invoice.customerName}</p>
                {invoice.customerEmail && <p className="text-slate-500">Email: {invoice.customerEmail}</p>}
                {invoice.customerPhone && <p className="text-slate-500">Phone: {invoice.customerPhone}</p>}
              </div>
            </div>
            <div className="space-y-2 sm:text-right">
              <p className="uppercase font-bold text-slate-400 tracking-wider">Invoice Timeline</p>
              <div className="space-y-1 text-slate-600">
                <p>
                  <span className="font-semibold">Invoice Date:</span> {new Date(invoice.invoiceDate).toLocaleDateString()}
                </p>
                {invoice.dueDate && (
                  <p>
                    <span className="font-semibold">Due Date:</span> {new Date(invoice.dueDate).toLocaleDateString()}
                  </p>
                )}
              </div>
            </div>
          </div>

          {/* Line Items Table */}
          <div className="space-y-4">
            <p className="text-[10px] uppercase font-bold tracking-widest text-slate-400">Line Items</p>
            <div className="overflow-x-auto">
              <table className="w-full text-xs text-left">
                <thead>
                  <tr className="border-b border-slate-100 text-slate-500 uppercase font-semibold">
                    <th className="py-2.5">Description</th>
                    <th className="py-2.5 text-right w-20">Quantity</th>
                    <th className="py-2.5 text-right w-28">Unit Price</th>
                    <th className="py-2.5 text-right w-28">Amount</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-50">
                  {invoice.items && invoice.items.length > 0 ? (
                    invoice.items.map((item, idx) => (
                      <tr key={idx}>
                        <td className="py-3 font-semibold text-slate-800">{item.description}</td>
                        <td className="py-3 text-right font-mono">{item.quantity}</td>
                        <td className="py-3 text-right font-mono">Rs. {Number(item.unitPrice).toLocaleString()}</td>
                        <td className="py-3 text-right font-mono font-semibold">
                          Rs. {Number(item.lineTotal || (item.quantity * item.unitPrice)).toLocaleString()}
                        </td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan="4" className="py-4 text-center text-slate-400">No items on this invoice.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          {/* Totals Summary */}
          <div className="border-t border-slate-100 pt-6 flex justify-end">
            <div className="w-64 space-y-2 text-xs">
              <div className="flex justify-between text-slate-500">
                <span>Subtotal:</span>
                <span className="font-mono">Rs. {Number(invoice.subTotal || 0).toLocaleString()}</span>
              </div>
              {invoice.discountAmount > 0 && (
                <div className="flex justify-between text-green-700 font-semibold">
                  <span>Loyalty Discount (10%):</span>
                  <span className="font-mono">- Rs. {Number(invoice.discountAmount).toLocaleString()}</span>
                </div>
              )}
              <div className="flex justify-between text-slate-500">
                <span>Tax Amount:</span>
                <span className="font-mono">Rs. {Number(invoice.taxAmount || 0).toLocaleString()}</span>
              </div>
              <div className="border-t border-slate-200 pt-2 flex justify-between font-bold text-slate-900 text-sm">
                <span>Total:</span>
                <span className="font-mono">Rs. {Number(invoice.totalAmount || 0).toLocaleString()}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </StaffLayout>
  );
}
